# SPDX-License-Identifier: CDDL-1.0
#
# Minimal run file for l2arc_dwpd_multidev_pos testing only
#

[DEFAULT]
pre = setup
quiet = False
pre_user = root
user = root
timeout = 600
post_user = root
post = cleanup
failsafe_user = root
failsafe = callbacks/zfs_failsafe
tags = ['functional']

[tests/functional/cache]
tests = ['cache_001_pos', 'cache_002_pos', 'cache_003_pos', 'cache_004_neg',
    'cache_005_neg', 'cache_006_pos', 'cache_007_neg', 'cache_008_neg',
    'cache_009_pos', 'cache_010_pos', 'cache_011_pos', 'cache_012_pos']
tags = ['functional', 'cache']

[tests/functional/l2arc]
tests = ['l2arc_arcstats_pos', 'l2arc_mfuonly_pos', 'l2arc_l2miss_pos',
    'l2arc_dwpd_pos', 'l2arc_dwpd_multidev_pos', 'l2arc_dwpd_persist_pos',
    'l2arc_parallel_writes_pos', 'persist_l2arc_001_pos', 'persist_l2arc_002_pos',
    'persist_l2arc_003_neg', 'persist_l2arc_004_pos', 'persist_l2arc_005_pos']
tags = ['functional', 'l2arc']
